#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install and configure Fish Shell
  hosts: all
  become: True
  tasks:
    - name: Install Fish
      apt: name=fish state=latest update_cache=true cache_valid_time=600

    - name: Create directory for fish
      file: path=/home/vagrant/.config/fish state=directory owner=vagrant group=vagrant mode=700

    - name: Add Fish predefined config
      copy: src=files/config.fish dest=/home/vagrant/.config/fish/config.fish owner=vagrant group=vagrant mode=664

    - name: Change default shell
      user: name=vagrant shell=/usr/bin/fish

    - name: Create directory for completions
      file: path=/home/vagrant/.config/fish/completions state=directory owner=vagrant group=vagrant mode=664

    - name: Install Docker completions file
      get_url: url=https://raw.github.com/barnybug/docker-fish-completion/master/docker.fish dest=/home/vagrant/.config/fish/completions/docker.fish mode=664

- name: Add useful scripts
  hosts: all
  become: True
  tasks:
    - name: Copy docker restart script
      copy: src=files/restart-without-mongo dest=/usr/local/bin/restart-without-mongo owner=vagrant mode=755
    - name: Copy registry login script
      copy: src=files/login-to-registry dest=/usr/local/bin/login-to-registry owner=vagrant mode=755

- name: Update XFCE Terminal default settings
  hosts: all
  become: True
  tasks:
    - name: Create directory for Terminal settings
      file: path=/home/vagrant/.config/xfce4/terminal state=directory owner=vagrant group=vagrant mode=775

    - name: Copy predefined terminal settings
      copy: src=files/terminalrc dest=/home/vagrant/.config/xfce4/terminal/terminalrc owner=vagrant mode=666

- name: Install and configure Vim
  hosts: all
  become: True
  tasks:
    - name: Install Vim
      apt: name=vim state=latest update_cache=true cache_valid_time=600

