#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install and configure Fish Shell
  hosts: Ubuntu
  become: True
  tasks:
    - name: Install Fish
      apt: name=fish state=latest update_cache=true cache_valid_time=600

    - name: Create directory for fish
      file: path=/home/vagrant/.config/fish state=directory owner=vagrant group=vagrant mode=700

    - name: Add Fish predefined config
      copy: src=files/config.fish dest=/home/vagrant/.config/fish/config.fish owner=vagrant group=vagrant mode=664

    - name: Change default shell
      user: name=vagrant shell=/usr/bin/fish

    - name: Create directory for completions
      file: path=/hove/vagrant/.config/fish/completions state=directory owner=vagrant group=vagrant mode=664

    - name: Install Docker completions file
      command: wget https://raw.github.com/barnybug/docker-fish-completion/master/docker.fish -O /hove/vagrant/.config/fish/completions/docker.fish

- name: Add Docker restart script
  hosts: Ubuntu
  become: True
  tasks:
    - name: Copy script
      copy: src=files/restart-without-mongo dest=/usr/local/bin/restart-without-mongo owner=vagrant mode=755

